---
services:
  transmission:
    build: .
    cap_add:
    - NET_ADMIN
    volumes:
    - ${DATA_VOLUME:-./data:/data}
    - ${CONF_VOLUME:-./config:/config}
    - rpc:/rpc
    env_file:
    - .env
    environment:
    - OPENVPN_USERNAME=${OPENVPN_USERNAME?error}
    - OPENVPN_PASSWORD=${OPENVPN_PASSWORD?error}
    - OPENVPN_PROVIDER=${OPENVPN_PROVIDER:-pia}
    - OPENVPN_CONFIG=${OPENVPN_CONFIG:-netherlands}
    - PGID=${PGID:-998}
    - PUID=${PUID:-1000}
    - TRANSMISSION_DOWNLOAD_DIR=${TRANSMISSION_DOWNLOAD_DIR:-/data/downloads}
    - TRANSMISSION_INCOMPLETE_DIR=${TRANSMISSION_INCOMPLETE_DIR:-/data/incomplete}
    - TRANSMISSION_WATCH_DIR=${TRANSMISSION_WATCH_DIR:-/data/torrents}
    - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=${TRANSMISSION_RPC_AUTHENTICATION_REQUIRED:-false}
    - LOG_TO_STDOUT=${LOG_TO_STDOUT:-true}
    restart: ${RESTART_POLICY:-unless-stopped}

  socat:
    image: alpine/socat
    command: TCP-LISTEN:9091,fork UNIX-CONNECT:/rpc/transmission.sock
    volumes:
    - rpc:/rpc
    ports:
    - ${HOST_LISTEN_PORT:-9091}:9091
    depends_on:
    - transmission
    restart: unless-stopped

volumes:
  rpc:
